version: '3'
services:

    nginx:
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./blog/public:/usr/share/nginx/html
            - ./nginx:/etc/nginx/conf.d:ro
            - ../letsencrypt:/etc/letsencrypt
            - ../ssl:/etc/nginx/ssl

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=paskal.07@gmail.com
            - LE_FQDN=terrty.net

    dnsmask:
        image: andyshinn/dnsmasq:latest
        hostname: dnsmasq
        restart: always
        container_name: dnsmasq

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "53:53"

        cap_add:
            - NET_ADMIN

    softethervpn:
        image: siomiz/softethervpn
        hostname: softethervpn
        restart: always
        container_name: softethervpn
        env_file: ../softethervpn.env

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "500:500/udp"
            - "4500:4500/udp"
            - "1701:1701/tcp"
            - "1194:1194/udp"
            - "5555:5555/tcp"
            - "992:992/tcp"

        cap_add:
            - NET_ADMIN

    socks_pub:
        image: dijedodol/simple-socks5-server:latest
        hostname: socks_pub
        restart: always
        container_name: socks_pub
        env_file: ../socks_pub.env

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "1080:1080/tcp"

    socks_telegram:
        image: dijedodol/simple-socks5-server:latest
        hostname: socks_telegram
        restart: always
        container_name: socks_telegram
        env_file: ../socks_telegram.env

        environment:
            - SSS_BIND=0.0.0.0:1088

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "1088:1088/tcp"

    socks:
        image: dijedodol/simple-socks5-server:latest
        hostname: socks
        restart: always
        container_name: socks
        env_file: ../socks.env

        environment:
            - SSS_BIND=0.0.0.0:1081

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "1081:1081/tcp"

    pointim_bot:
        build: ./pointim_bot
        image: paskal/pointim_bot
        hostname: pointim_bot
        restart: always
        container_name: pointim_bot
        env_file: ../pointim_bot.env

        logging:
          driver: none

        volumes:
            - /root/cache.bin:/usr/pointim_bot/cache.bin
