version: '2'
services:
    nginx:
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx
        depends_on:
            - monit
            - grafana

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        volumes:
            # terrty.net blog source code
            - ./blog/public:/usr/share/nginx/html
            # ksinia.net source code
            - ./docker/ksinia/public/:/usr/share/nginx/html2
            - ./config/nginx/terrty.net.conf:/etc/nginx/service1.conf
            - ./config/nginx/ksinia.net.conf:/etc/nginx/service2.conf
            - ./config/nginx/theatrestudio.ru.conf:/etc/nginx/service3.conf
            - ./config/nginx/monit.terrty.net.conf:/etc/nginx/service4.conf
            - ./config/nginx/grafana.terrty.net.conf:/etc/nginx/service5.conf
            - ./config/nginx/zabbix.terrty.net.conf:/etc/nginx/service6.conf
            - ./config/nginx/ssl.conf:/etc/nginx/ssl.conf
            # nginx ssl certificate to prevent renewal on each restart
            - ./docker/ssl:/etc/nginx/ssl

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=paskal.07@gmail.com
            - LE_FQDN=grafana.terrty.net,zabbix.terrty.net,monit.terrty.net,terrty.net,ksinia.net
    monit:
        build: ./monit
        image: paskal/monit-telegram
        container_name: monit
        hostname: monit
        expose:
            - "2812"
        # uncomment for local tests
        # ports:
        # - 2812:2812
        env_file: docker/environment/monit.env
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
        volumes:
            # do `chown 1000:1000 ./config/monit/monitrc` as otherwise there will be permission error on start
            - ./config/monit/monitrc:/etc/monitrc:ro
            - ./config/monit/web.monit:/etc/monit.d/web.monit:ro
        restart: unless-stopped
        user: monit:users

    grafana:
        image: grafana/grafana
        restart: always
        volumes:
            - ./config/grafana.ini:/etc/grafana/grafana.ini:ro
            # Data persistence
            # to make it work run chown 472:472 -R ./docker/grafana-data
            - ./docker/grafana-data:/var/lib/grafana
        expose:
            - "3000"
        # uncomment for local tests
        # ports:
        #     - 3000:3000
        environment:
            - TZ=UTC
            - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
            - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource

    zabbix-web:
        image: zabbix/zabbix-web-nginx-mysql:latest
        container_name: zabbix-web
        restart: always
        depends_on:
            - mysql-server
            - zabbix-server
        # MYSQL_DATABASE, MYSQL_PASSWORD, MYSQL_USER
        env_file: docker/environment/mysql.env
        environment:
            - TZ=UTC
            - DB_SERVER_HOST=mysql-server
            - ZBX_SERVER_HOST=zabbix-server
            - PHP_TZ=Europe/Moscow
        expose:
            - "8080"
        # uncomment for local tests
        # ports:
        #     - "8080:8080"

    zabbix-server:
        image: zabbix/zabbix-server-mysql:latest
        container_name: zabbix-server
        restart: always
        depends_on:
            - mysql-server
        # MYSQL_DATABASE, MYSQL_PASSWORD, MYSQL_USER
        env_file: docker/environment/mysql.env
        environment:
            - TZ=UTC
            - DB_SERVER_HOST=mysql-server
        ports:
            - "10051:10051"

    mysql-server:
        image: mysql:8.0
        container_name: mysql-server
        command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
        # MYSQL_DATABASE, MYSQL_PASSWORD, MYSQL_USER
        env_file: docker/environment/mysql.env
        environment:
            - TZ=UTC
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        expose:
            - "3306"
        # uncomment for local tests
        # ports:
        # - 3306:3306
        volumes:
            # Data persistence
            - ./docker/mysql-data:/var/lib/mysql
        # fix for `mbind: Operation not permitted`
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        restart: always

    softethervpn:
        image: siomiz/softethervpn:alpine
        hostname: softethervpn
        restart: always
        container_name: softethervpn
        env_file: docker/environment/softethervpn.env

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        ports:
            # OpenVPN, unused
            # - "1194:1194/udp"
            - "500:500/udp"
            - "4500:4500/udp"
            - "1701:1701/tcp"
            - "5555:5555/tcp"
            - "992:992/tcp"

        cap_add:
            - NET_ADMIN

    socks_telegram:
        image: dijedodol/simple-socks5-server:latest
        hostname: socks_telegram
        restart: always
        container_name: socks_telegram
        env_file: docker/environment/socks_telegram.env

        environment:
            - SSS_BIND=0.0.0.0:1088

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        ports:
            - "1088:1088/tcp"
