version: '2'
services:
    nginx:
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./blog/public:/usr/share/nginx/html
            - ../ksinia/public/:/usr/share/nginx/html2
            - ./nginx/terrty.net.conf:/etc/nginx/service1.conf
            - ./nginx/ksinia.net.conf:/etc/nginx/service2.conf
            - ./nginx/theatrestudio.ru.conf:/etc/nginx/service3.conf
#            - ./nginx/mon.terrty.net.conf:/etc/nginx/service4.conf
            - ./nginx/ssl.conf:/etc/nginx/ssl.conf
            - ../ssl:/etc/nginx/ssl

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=paskal.07@gmail.com
            - LE_FQDN=mon.terrty.net,terrty.net,ksinia.net
    monit:
        build: ./monit
        image: paskal/monit-telegram
        container_name: monit
        hostname: monit
        expose:
        - "2812"
        # ports:
        # - 2812:2812
        env_file: ../monit.env
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"
        volumes:
        - ./monit/monitrc:/etc/monitrc
        - ./monit/web.monit:/etc/monit.d/web.monit
        restart: unless-stopped
        user: monit:users

    softethervpn:
        image: siomiz/softethervpn:alpine
        hostname: softethervpn
        restart: always
        container_name: softethervpn
        env_file: ../softethervpn.env

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
#            - "1194:1194/udp" # OpenVPN, unused
            - "500:500/udp"
            - "4500:4500/udp"
            - "1701:1701/tcp"
            - "5555:5555/tcp"
            - "992:992/tcp"

        cap_add:
            - NET_ADMIN

    socks_telegram:
        image: dijedodol/simple-socks5-server:latest
        hostname: socks_telegram
        restart: always
        container_name: socks_telegram
        env_file: ../socks_telegram.env

        environment:
            - SSS_BIND=0.0.0.0:1088

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "1088:1088/tcp"
